
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POETRY_VIRTUALENVS_CREATE=false

  test:
    build: .
    volumes:
      - .:/app
    command: ["poetry", "run", "pytest"]